// src/components/layout/ThePlayerPanel/AudioPanel/MainControlsPanel/QueueButton.vue
<template>
  <div
    class="ui tiny compact icon button"
    :class="{
      disabled: !queueTracksCount,
      basic: !isQueuePanelVisible
    }"
    @click="handleClick"
  >
    <i class="list ul icon" />
  </div>
</template>

<script>
import { mapGetters, mapState } from 'vuex'
import { toggleQueuePanel } from '#/actions/layout'

export default {
  name: 'QueueButton',
  computed: {
    ...mapGetters('queue', {
      queueTracksCount: 'tracksCount'
    }),
    ...mapState('layout', [
      'isQueuePanelVisible'
    ])
  },
  methods: {
    handleClick () {
      toggleQueuePanel()
    }
  }
}
</script>

<style lang="sass" scoped></style>

// src/components/global/player/panel/controls/extra/QueueButton.jsx
import React from 'react'
import { Button, Popup } from 'semantic-ui-react'

export default class QueueButton extends React.PureComponent {
  buttonData () {
    const { queue, toggleQueuePanel } = this.props

    return (
      <Button
        basic
        compact
        size="tiny"
        icon="numbered list"
        disabled={!queue}
        onClick={toggleQueuePanel}
      />
    )
  }

  render () {
    return (
      <Popup
        inverted
        positionFixed
        on="hover"
        position="top center"
        content="Queue"
        className="playerPanelExtraPopup"
        trigger={this.buttonData()}
      />
    )
  }
}
