// src/components/layout/TheQueuePanel/HeaderSection/ShuffleButton.vue
<template>
  <div
    class="ui compact icon button shuffle-button"
    :class="{ basic: !isQueueShuffle }"
    @click="handleClick"
  >
    <i class="random icon" />
  </div>
</template>

<script>
import { mapState } from 'vuex'
import { toggleIsShuffle as toggleIsQueueShuffle } from '#/actions/queue'

export default {
  name: 'ShuffleButton',
  computed: {
    ...mapState('queue', {
      isQueueShuffle: 'isShuffle'
    })
  },
  methods: {
    handleClick () {
      toggleIsQueueShuffle()
    }
  }
}
</script>

<style lang="sass" scoped>
.shuffle-button
  @extend .no-margin, .no-shadow
</style>

// src/components/global/player/panel/controls/main/ShuffleButton.jsx
import React from 'react'
import { Button } from 'semantic-ui-react'

export default class ShuffleButton extends React.PureComponent {
  render () {
    const { queue, isShuffle, toggleShuffle } = this.props

    return (
      <Button
        compact
        size="tiny"
        icon="shuffle"
        disabled={!queue}
        basic={!isShuffle}
        onClick={toggleShuffle}
      />
    )
  }
}
