// src/components/layout/ThePlayerPanel/AudioPanel/MainControlsPanel/ShuffleButton.vue
<template>
  <div
    class="ui tiny compact icon button"
    :class="{
      disabled: isQueueEmpty,
      basic: !isQueueShuffle
    }"
    @click="handleClick"
  >
    <i class="random icon" />
  </div>
</template>

<script>
import { mapState } from 'vuex'
import {
  getTracksCount as getQueueTracksCount,
  toggleIsShuffle as toggleIsQueueShuffle
} from '#/actions/queue'

export default {
  name: 'ShuffleButton',
  computed: {
    ...mapState('queue', {
      isQueueShuffle: 'isShuffle'
    }),
    isQueueEmpty () {
      return !getQueueTracksCount()
    }
  },
  methods: {
    handleClick () {
      toggleIsQueueShuffle()
    }
  }
}
</script>

<style lang="sass" scoped></style>

// src/components/global/player/panel/controls/main/ShuffleButton.jsx
import React from 'react'
import { Button } from 'semantic-ui-react'

export default class ShuffleButton extends React.PureComponent {
  render () {
    const { queue, isShuffle, toggleShuffle } = this.props

    return (
      <Button
        compact
        size="tiny"
        icon="shuffle"
        disabled={!queue}
        basic={!isShuffle}
        onClick={toggleShuffle}
      />
    )
  }
}
